---
apiVersion: v1
kind: Pod
metadata:
  name: prashu-pod
  labels:
    app: nginx
spec:
  containers:
    - name: prashu-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prashu-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 35001
      targetPort: 80