---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: prashu-pod
    app: nginx
spec:
  containers:
    - name: prashu-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP